name: Windows Alternative Compilers
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  mingw:
    if: github.repository_owner == 'aws'
    runs-on: windows-latest
    steps:
      - name: Install NASM
        uses: ilammy/setup-nasm@v1.5.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        id: setup_mingw
        with:
          static: 0
      - name: Setup CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: ${{ steps.setup_mingw.outputs.gcc }}
          cxx-compiler: ${{ steps.setup_mingw.outputs.gxx }}
          options: |
            CMAKE_SYSTEM_NAME=Windows \
            CMAKE_SYSTEM_PROCESSOR=x86_64 \
            CMAKE_BUILD_TOOL=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/ninja.exe \
            CMAKE_FIND_ROOT_PATH=C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64 \
            CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
            CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
            CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
            CMAKE_BUILD_TYPE=Release \
      - name: Build Project
        run: cmake --build ./build --target all
      - name: Run tests
        run: cmake --build ./build --target run_tests
  clang:
    if: github.repository_owner == 'aws'
    runs-on: windows-latest
    steps:
      - name: Install NASM
        uses: ilammy/setup-nasm@v1.5.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        id: clang
        with:
          version: 16
          env: true
      - name: Setup CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: "C:/Program Files/LLVM/bin/clang.exe"
          cxx-compiler: "C:/Program Files/LLVM/bin/clang++.exe"
          options: |
            CMAKE_SYSTEM_NAME=Windows \
            CMAKE_SYSTEM_PROCESSOR=x86_64 \
            CMAKE_BUILD_TOOL=ninja.exe \
            CMAKE_BUILD_TYPE=Release \
      - name: Build Project
        run: cmake --build ./build --target all
      - name: Run tests
        run: cmake --build ./build --target run_tests
